.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tcccoin_qt test_tcccoin_qt
clean: FORCE
	$(MAKE) -C .. tcccoin_qt_clean test_tcccoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_tcccoin_qt_check
tcccoin-qt tcccoin-qt.exe: FORCE
	 $(MAKE) -C .. tcccoin_qt
